name: C/C++ CI

on:
  push:
    branches:
        - main
        - param/uint32_t
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: cd tests && ./script_compile_run_tests.sh
